/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserKind = "admin" | "user";

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  kind: UserKind | null;
  password: string;
  username: string;
}

export interface DB {
  users: Users;
}
